version: 0.2
env:
  PROJECT: DotnetDemo
phases:
  install:
    runtime-version:
      dotnet: 3.1

  build:
    commands:
      - dotnet build
      - dotnet publish -c release -r win10-x64 -o ./build_ouput ${PROJECT}.csproj

artifacts:
  files:
    - build_ouput/**/*
    - appspec.yml